name: Upload to codecov

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test python API
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install requirements
      run: |
        pip install -r requirements-test.txt
        pip install -e .
    - name: Run tests and collect coverage
      env: # Or as an environment variable
        HOST: ${{ secrets.HOST }}
        SENDER_NAME: ${{ secrets.SENDER_NAME }}
        SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
        RECEIVER_NAME: ${{ secrets.RECEIVER_NAME }}
        RECEIVER_PASSWORD: ${{ secrets.RECEIVER_PASSWORD }}
      run: pytest --cov .
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
